'use client';
import type { Metadata } from 'next';
import { useState } from 'react';
import { Inter } from 'next/font/google';
import { Providers } from '@/providers';
import Header from '@/src/Components/Header';
import { Box } from '@chakra-ui/react';
import Sidebar from '@/src/Components/Sidebar';
import Footer from '@/src/Components/Footer';
import { AOSInit } from '@/src/utils/aos';
import { usePathname } from 'next/navigation';
import ToasterContext from '../lib/ToasterContext';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [showSide, setShowSide] = useState<boolean>(false);
  const pathname = usePathname();
  const noNav =
    pathname?.startsWith('/login') || pathname?.startsWith('/register');

  return (
    <html lang="en">
      <AOSInit />
      <body>
        <Providers>
          <ToasterContext />

          {noNav ? (
            <Box>{children}</Box>
          ) : (
            <Box>
              <Sidebar showSide={showSide} setShowSide={setShowSide} />
              <Header showSide={showSide} setShowSide={setShowSide} />
              <Box as="main" minH={'90vh'}>
                {children}
              </Box>
              <Footer />
            </Box>
          )}
        </Providers>
      </body>
    </html>
  );
}
